//! gRPC server implementation for Tardigrade Git module
//!
//! This module implements the gRPC server for Git operations.

use crate::error::GitError;
use crate::models::{
    branch::{Branch, CreateBranchInput, ListBranchesQuery, UpdateBranchInput},
    commit::{Commit, CreateCommitInput, ListCommitsQuery},
    CreateRepositoryInput, ListRepositoriesQuery, Repository, UpdateRepositoryInput,
};
use crate::repository::*;
use std::pin::Pin;
use std::sync::Arc;
use tokio::sync::Mutex;
use tokio_stream::wrappers::ReceiverStream;
use tonic::{Request, Response, Status, Streaming};
use uuid::Uuid;

// Include the generated gRPC code
// This will be generated by tonic-build from the .proto file
// For now, we'll define the types manually to avoid build issues

/// Git gRPC service server
#[derive(Debug, Default)]
pub struct GitGrpcServer {
    pool: Arc<Mutex<sqlx::postgres::PgPool>>,
}

impl GitGrpcServer {
    /// Create a new gRPC server instance
    pub fn new(pool: sqlx::postgres::PgPool) -> Self {
        Self {
            pool: Arc::new(Mutex::new(pool)),
        }
    }
}

/// Manual implementation of gRPC service traits
/// In a real implementation, these would be generated from the .proto file

/// Repository service implementation
#[async_trait::async_trait]
impl GitGrpcServer {
    /// Create a new repository
    pub async fn create_repository(
        &self,
        request: CreateRepositoryRequest,
    ) -> Result<RepositoryResponse, Status> {
        let pool = self.pool.lock().await;
        
        let input = CreateRepositoryInput {
            name: request.name,
            description: request.description,
            is_private: request.is_private,
            default_branch: request.default_branch,
        };
        
        let owner_id = Uuid::parse_str(&request.owner_id)
            .map_err(|_| Status::invalid_argument("Invalid owner ID"))?;
        
        let repo = create_repository(&pool, input, owner_id).await
            .map_err(|e| map_git_error_to_status(e))?;
        
        Ok(RepositoryResponse::from(repo))
    }

    /// Get a repository by ID
    pub async fn get_repository(
        &self,
        request: GetRepositoryRequest,
    ) -> Result<RepositoryResponse, Status> {
        let pool = self.pool.lock().await;
        
        let id = Uuid::parse_str(&request.id)
            .map_err(|_| Status::invalid_argument("Invalid repository ID"))?;
        
        let repo = get_repository(&pool, id).await
            .map_err(|e| map_git_error_to_status(e))?
            .ok_or_else(|| Status::not_found("Repository not found"))?;
        
        Ok(RepositoryResponse::from(repo))
    }

    /// List repositories
    pub async fn list_repositories(
        &self,
        request: ListRepositoriesRequest,
    ) -> Result<ListRepositoriesResponse, Status> {
        let pool = self.pool.lock().await;
        
        let query = ListRepositoriesQuery {
            owner_id: request.owner_id.map(|id| Uuid::parse_str(&id).unwrap_or(Uuid::nil())),
            page: request.page,
            page_size: request.page_size,
            search: request.search,
            is_private: request.is_private,
        };
        
        let response = list_repositories(&pool, query).await
            .map_err(|e| map_git_error_to_status(e))?;
        
        Ok(ListRepositoriesResponse::from(response))
    }

    /// Update a repository
    pub async fn update_repository(
        &self,
        request: UpdateRepositoryRequest,
    ) -> Result<RepositoryResponse, Status> {
        let pool = self.pool.lock().await;
        
        let id = Uuid::parse_str(&request.id)
            .map_err(|_| Status::invalid_argument("Invalid repository ID"))?;
        let owner_id = Uuid::parse_str(&request.owner_id.unwrap_or_default())
            .map_err(|_| Status::invalid_argument("Invalid owner ID"))?;
        
        let input = UpdateRepositoryInput {
            name: request.name,
            description: request.description,
            is_private: request.is_private,
            default_branch: request.default_branch,
        };
        
        let repo = update_repository(&pool, id, owner_id, input).await
            .map_err(|e| map_git_error_to_status(e))?;
        
        Ok(RepositoryResponse::from(repo))
    }

    /// Delete a repository
    pub async fn delete_repository(
        &self,
        request: DeleteRepositoryRequest,
    ) -> Result<DeleteResponse, Status> {
        let pool = self.pool.lock().await;
        
        let id = Uuid::parse_str(&request.id)
            .map_err(|_| Status::invalid_argument("Invalid repository ID"))?;
        let owner_id = Uuid::parse_str(&request.owner_id)
            .map_err(|_| Status::invalid_argument("Invalid owner ID"))?;
        
        delete_repository(&pool, id, owner_id).await
            .map_err(|e| map_git_error_to_status(e))?;
        
        Ok(DeleteResponse {
            success: true,
            message: "Repository deleted successfully".to_string(),
        })
    }

    /// Create a new branch
    pub async fn create_branch(
        &self,
        request: CreateBranchRequest,
    ) -> Result<BranchResponse, Status> {
        let pool = self.pool.lock().await;
        
        let repository_id = Uuid::parse_str(&request.repository_id)
            .map_err(|_| Status::invalid_argument("Invalid repository ID"))?;
        
        let input = CreateBranchInput {
            name: request.name,
            commit_hash: request.commit_hash,
            is_default: request.is_default,
        };
        
        let branch = crate::repository::branch::create_branch(&pool, repository_id, input).await
            .map_err(|e| map_git_error_to_status(e))?;
        
        Ok(BranchResponse::from(branch))
    }

    /// Get a branch by ID
    pub async fn get_branch(
        &self,
        request: GetBranchRequest,
    ) -> Result<BranchResponse, Status> {
        let pool = self.pool.lock().await;
        
        let id = Uuid::parse_str(&request.id)
            .map_err(|_| Status::invalid_argument("Invalid branch ID"))?;
        
        let branch = crate::repository::branch::get_branch(&pool, id).await
            .map_err(|e| map_git_error_to_status(e))?
            .ok_or_else(|| Status::not_found("Branch not found"))?;
        
        Ok(BranchResponse::from(branch))
    }

    /// List branches for a repository
    pub async fn list_branches(
        &self,
        request: ListBranchesRequest,
    ) -> Result<ListBranchesResponse, Status> {
        let pool = self.pool.lock().await;
        
        let repository_id = Uuid::parse_str(&request.repository_id)
            .map_err(|_| Status::invalid_argument("Invalid repository ID"))?;
        
        let query = ListBranchesQuery {
            repository_id,
            page: request.page,
            page_size: request.page_size,
            search: None,
        };
        
        let response = crate::repository::branch::list_branches(&pool, query).await
            .map_err(|e| map_git_error_to_status(e))?;
        
        Ok(ListBranchesResponse::from(response))
    }

    /// Update a branch
    pub async fn update_branch(
        &self,
        request: UpdateBranchRequest,
    ) -> Result<BranchResponse, Status> {
        let pool = self.pool.lock().await;
        
        let id = Uuid::parse_str(&request.id)
            .map_err(|_| Status::invalid_argument("Invalid branch ID"))?;
        
        let input = UpdateBranchInput {
            name: request.name,
            commit_hash: request.commit_hash,
            is_default: request.is_default,
        };
        
        let branch = crate::repository::branch::update_branch(&pool, id, input).await
            .map_err(|e| map_git_error_to_status(e))?;
        
        Ok(BranchResponse::from(branch))
    }

    /// Delete a branch
    pub async fn delete_branch(
        &self,
        request: DeleteBranchRequest,
    ) -> Result<DeleteResponse, Status> {
        let pool = self.pool.lock().await;
        
        let id = Uuid::parse_str(&request.id)
            .map_err(|_| Status::invalid_argument("Invalid branch ID"))?;
        
        crate::repository::branch::delete_branch(&pool, id).await
            .map_err(|e| map_git_error_to_status(e))?;
        
        Ok(DeleteResponse {
            success: true,
            message: "Branch deleted successfully".to_string(),
        })
    }

    /// Get the default branch for a repository
    pub async fn get_default_branch(
        &self,
        request: GetDefaultBranchRequest,
    ) -> Result<BranchResponse, Status> {
        let pool = self.pool.lock().await;
        
        let repository_id = Uuid::parse_str(&request.repository_id)
            .map_err(|_| Status::invalid_argument("Invalid repository ID"))?;
        
        let branch = crate::repository::branch::get_default_branch(&pool, repository_id).await
            .map_err(|e| map_git_error_to_status(e))?
            .ok_or_else(|| Status::not_found("Default branch not found"))?;
        
        Ok(BranchResponse::from(branch))
    }

    /// Create a new commit
    pub async fn create_commit(
        &self,
        request: CreateCommitRequest,
    ) -> Result<CommitResponse, Status> {
        let pool = self.pool.lock().await;
        
        let repository_id = Uuid::parse_str(&request.repository_id)
            .map_err(|_| Status::invalid_argument("Invalid repository ID"))?;
        
        let input = CreateCommitInput {
            hash: request.hash,
            parent_hash: request.parent_hash,
            message: request.message,
            author_name: request.author_name,
            author_email: request.author_email,
            committer_name: request.committer_name,
            committer_email: request.committer_email,
            branch_name: request.branch_name,
        };
        
        let commit = crate::repository::commit::create_commit(&pool, repository_id, input).await
            .map_err(|e| map_git_error_to_status(e))?;
        
        Ok(CommitResponse::from(commit))
    }

    /// Get a commit by ID
    pub async fn get_commit(
        &self,
        request: GetCommitRequest,
    ) -> Result<CommitResponse, Status> {
        let pool = self.pool.lock().await;
        
        let id = Uuid::parse_str(&request.id)
            .map_err(|_| Status::invalid_argument("Invalid commit ID"))?;
        
        let commit = crate::repository::commit::get_commit(&pool, id).await
            .map_err(|e| map_git_error_to_status(e))?
            .ok_or_else(|| Status::not_found("Commit not found"))?;
        
        Ok(CommitResponse::from(commit))
    }

    /// List commits for a repository
    pub async fn list_commits(
        &self,
        request: ListCommitsRequest,
    ) -> Result<ListCommitsResponse, Status> {
        let pool = self.pool.lock().await;
        
        let repository_id = Uuid::parse_str(&request.repository_id)
            .map_err(|_| Status::invalid_argument("Invalid repository ID"))?;
        
        let query = ListCommitsQuery {
            repository_id,
            branch_name: request.branch_name,
            page: request.page,
            page_size: request.page_size,
            search: request.search,
        };
        
        let response = crate::repository::commit::list_commits(&pool, query).await
            .map_err(|e| map_git_error_to_status(e))?;
        
        Ok(ListCommitsResponse::from(response))
    }

    /// Get the latest commit for a branch
    pub async fn get_latest_commit(
        &self,
        request: GetLatestCommitRequest,
    ) -> Result<CommitResponse, Status> {
        let pool = self.pool.lock().await;
        
        let repository_id = Uuid::parse_str(&request.repository_id)
            .map_err(|_| Status::invalid_argument("Invalid repository ID"))?;
        
        let commit = crate::repository::commit::get_latest_commit(&pool, repository_id, &request.branch_name).await
            .map_err(|e| map_git_error_to_status(e))?
            .ok_or_else(|| Status::not_found("Latest commit not found"))?;
        
        Ok(CommitResponse::from(commit))
    }

    /// List commits for a specific branch
    pub async fn list_commits_by_branch(
        &self,
        request: ListCommitsByBranchRequest,
    ) -> Result<ListCommitsResponse, Status> {
        let pool = self.pool.lock().await;
        
        let repository_id = Uuid::parse_str(&request.repository_id)
            .map_err(|_| Status::invalid_argument("Invalid repository ID"))?;
        
        let query = ListCommitsQuery {
            repository_id,
            branch_name: Some(request.branch_name),
            page: request.page,
            page_size: request.page_size,
            search: None,
        };
        
        let response = crate::repository::commit::list_commits(&pool, query).await
            .map_err(|e| map_git_error_to_status(e))?;
        
        Ok(ListCommitsResponse::from(response))
    }

    /// Health check endpoint
    pub async fn health_check(
        &self,
        _request: HealthCheckRequest,
    ) -> Result<HealthCheckResponse, Status> {
        Ok(HealthCheckResponse {
            status: "healthy".to_string(),
            module: "git".to_string(),
            version: "0.1.0".to_string(),
            timestamp: chrono::Utc::now().to_rfc3339(),
        })
    }
}

/// Map GitError to gRPC Status
fn map_git_error_to_status(err: GitError) -> Status {
    match err {
        GitError::RepositoryNotFound => Status::not_found("Repository not found"),
        GitError::RepositoryAlreadyExists(name) => Status::already_exists(format!("Repository '{}' already exists", name)),
        GitError::BranchNotFound => Status::not_found("Branch not found"),
        GitError::BranchAlreadyExists(name) => Status::already_exists(format!("Branch '{}' already exists", name)),
        GitError::CannotDeleteDefaultBranch => Status::invalid_argument("Cannot delete default branch"),
        GitError::CommitNotFound => Status::not_found("Commit not found"),
        GitError::ParentCommitNotFound(hash) => Status::not_found(format!("Parent commit '{}' not found", hash)),
        GitError::PermissionDenied => Status::permission_denied("Permission denied"),
        GitError::ValidationError(msg) => Status::invalid_argument(msg),
        GitError::InvalidInput(msg) => Status::invalid_argument(msg),
        GitError::InvalidUuid(msg) => Status::invalid_argument(msg),
        GitError::Database(_) => Status::internal("Database error"),
        GitError::InternalError(msg) => Status::internal(msg),
        GitError::ConfigError(msg) => Status::internal(msg),
    }
}

/// Request and Response types for gRPC
/// These would normally be generated from the .proto file

#[derive(Debug, Default)]
pub struct CreateRepositoryRequest {
    pub name: String,
    pub description: Option<String>,
    pub is_private: bool,
    pub default_branch: String,
    pub owner_id: String,
}

#[derive(Debug, Default)]
pub struct GetRepositoryRequest {
    pub id: String,
}

#[derive(Debug, Default)]
pub struct ListRepositoriesRequest {
    pub owner_id: Option<String>,
    pub page: i32,
    pub page_size: i32,
    pub search: Option<String>,
    pub is_private: Option<bool>,
}

#[derive(Debug, Default)]
pub struct UpdateRepositoryRequest {
    pub id: String,
    pub owner_id: Option<String>,
    pub name: Option<String>,
    pub description: Option<String>,
    pub is_private: Option<bool>,
    pub default_branch: Option<String>,
}

#[derive(Debug, Default)]
pub struct DeleteRepositoryRequest {
    pub id: String,
    pub owner_id: String,
}

#[derive(Debug, Default)]
pub struct RepositoryResponse {
    pub id: String,
    pub name: String,
    pub description: Option<String>,
    pub is_private: bool,
    pub owner_id: String,
    pub default_branch: String,
    pub created_at: String,
    pub updated_at: String,
}

impl From<Repository> for RepositoryResponse {
    fn from(repo: Repository) -> Self {
        Self {
            id: repo.id.to_string(),
            name: repo.name,
            description: repo.description,
            is_private: repo.is_private,
            owner_id: repo.owner_id.to_string(),
            default_branch: repo.default_branch,
            created_at: repo.created_at.to_rfc3339(),
            updated_at: repo.updated_at.to_rfc3339(),
        }
    }
}

#[derive(Debug, Default)]
pub struct ListRepositoriesResponse {
    pub repositories: Vec<RepositoryResponse>,
    pub page: i32,
    pub page_size: i32,
    pub total: i64,
    pub total_pages: i32,
}

impl From<crate::models::PaginatedResponse<Repository>> for ListRepositoriesResponse {
    fn from(response: crate::models::PaginatedResponse<Repository>) -> Self {
        Self {
            repositories: response.data.into_iter().map(RepositoryResponse::from).collect(),
            page: response.page,
            page_size: response.page_size,
            total: response.total,
            total_pages: response.total_pages,
        }
    }
}

#[derive(Debug, Default)]
pub struct CreateBranchRequest {
    pub repository_id: String,
    pub name: String,
    pub commit_hash: String,
    pub is_default: bool,
}

#[derive(Debug, Default)]
pub struct GetBranchRequest {
    pub id: String,
}

#[derive(Debug, Default)]
pub struct ListBranchesRequest {
    pub repository_id: String,
    pub page: i32,
    pub page_size: i32,
}

#[derive(Debug, Default)]
pub struct UpdateBranchRequest {
    pub id: String,
    pub name: Option<String>,
    pub commit_hash: Option<String>,
    pub is_default: Option<bool>,
}

#[derive(Debug, Default)]
pub struct DeleteBranchRequest {
    pub id: String,
}

#[derive(Debug, Default)]
pub struct GetDefaultBranchRequest {
    pub repository_id: String,
}

#[derive(Debug, Default)]
pub struct BranchResponse {
    pub id: String,
    pub repository_id: String,
    pub name: String,
    pub commit_hash: String,
    pub is_default: bool,
    pub created_at: String,
    pub updated_at: String,
}

impl From<Branch> for BranchResponse {
    fn from(branch: Branch) -> Self {
        Self {
            id: branch.id.to_string(),
            repository_id: branch.repository_id.to_string(),
            name: branch.name,
            commit_hash: branch.commit_hash,
            is_default: branch.is_default,
            created_at: branch.created_at.to_rfc3339(),
            updated_at: branch.updated_at.to_rfc3339(),
        }
    }
}

#[derive(Debug, Default)]
pub struct ListBranchesResponse {
    pub branches: Vec<BranchResponse>,
    pub page: i32,
    pub page_size: i32,
    pub total: i64,
    pub total_pages: i32,
}

impl From<crate::models::PaginatedResponse<Branch>> for ListBranchesResponse {
    fn from(response: crate::models::PaginatedResponse<Branch>) -> Self {
        Self {
            branches: response.data.into_iter().map(BranchResponse::from).collect(),
            page: response.page,
            page_size: response.page_size,
            total: response.total,
            total_pages: response.total_pages,
        }
    }
}

#[derive(Debug, Default)]
pub struct CreateCommitRequest {
    pub repository_id: String,
    pub hash: String,
    pub parent_hash: Option<String>,
    pub message: String,
    pub author_name: String,
    pub author_email: String,
    pub committer_name: Option<String>,
    pub committer_email: Option<String>,
    pub branch_name: String,
}

#[derive(Debug, Default)]
pub struct GetCommitRequest {
    pub id: String,
}

#[derive(Debug, Default)]
pub struct ListCommitsRequest {
    pub repository_id: String,
    pub branch_name: Option<String>,
    pub page: i32,
    pub page_size: i32,
    pub search: Option<String>,
}

#[derive(Debug, Default)]
pub struct GetLatestCommitRequest {
    pub repository_id: String,
    pub branch_name: String,
}

#[derive(Debug, Default)]
pub struct ListCommitsByBranchRequest {
    pub repository_id: String,
    pub branch_name: String,
    pub page: i32,
    pub page_size: i32,
}

#[derive(Debug, Default)]
pub struct CommitResponse {
    pub id: String,
    pub repository_id: String,
    pub hash: String,
    pub parent_hash: Option<String>,
    pub message: String,
    pub author_name: String,
    pub author_email: String,
    pub committer_name: Option<String>,
    pub committer_email: Option<String>,
    pub branch_name: String,
    pub created_at: String,
}

impl From<Commit> for CommitResponse {
    fn from(commit: Commit) -> Self {
        Self {
            id: commit.id.to_string(),
            repository_id: commit.repository_id.to_string(),
            hash: commit.hash,
            parent_hash: commit.parent_hash,
            message: commit.message,
            author_name: commit.author_name,
            author_email: commit.author_email,
            committer_name: commit.committer_name,
            committer_email: commit.committer_email,
            branch_name: commit.branch_name,
            created_at: commit.created_at.to_rfc3339(),
        }
    }
}

#[derive(Debug, Default)]
pub struct ListCommitsResponse {
    pub commits: Vec<CommitResponse>,
    pub page: i32,
    pub page_size: i32,
    pub total: i64,
    pub total_pages: i32,
}

impl From<crate::models::PaginatedResponse<Commit>> for ListCommitsResponse {
    fn from(response: crate::models::PaginatedResponse<Commit>) -> Self {
        Self {
            commits: response.data.into_iter().map(CommitResponse::from).collect(),
            page: response.page,
            page_size: response.page_size,
            total: response.total,
            total_pages: response.total_pages,
        }
    }
}

#[derive(Debug, Default)]
pub struct DeleteResponse {
    pub success: bool,
    pub message: String,
}

#[derive(Debug, Default)]
pub struct HealthCheckRequest;

#[derive(Debug, Default)]
pub struct HealthCheckResponse {
    pub status: String,
    pub module: String,
    pub version: String,
    pub timestamp: String,
}
